config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only:[:create, :destroy]
  resources :follows, only:[:create, :destroy]
  devise_for :users
  resources :users, only:[:show]
  root 'welcome#index'
  get 'my_portfolio',to: "users#my_portfolio"
  get 'my_friends',to: "users#my_friends"
  get 'search_stock', to: "stocks#search"
  get 'update_stocks', to: "stocks#update_stocks"
  get 'search_friend', to: "users#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

	has_many :user_stocks
	has_many :users, through: :user_stocks

	validates :name, :ticker, presence: true 
	
	def update_price
		self.last_price=self.class.iex_client.price(ticker)
		self.save
	end


	def self.new_lookup(ticker_symbol)
  	client = iex_client
		begin
			client.price(ticker_symbol)
			new(ticker: ticker_symbol,  name:client.company(ticker_symbol).company_name,
					 last_price: client.price(ticker_symbol))
		rescue => exception
			return nil 
		end
	end
	
	def self.check_db(ticker_symbol)
		where(ticker: ticker_symbol).first
	end

	
	def self.iex_client
		client = IEX::Api::Client.new(
  			publishable_token: 
  				Rails.application.credentials.iex_client[:sand_box_key],
  			endpoint: 'https://sandbox.iexapis.com/v1')
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_stock
	has_many :stocks, through: :user_stock


  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :friends, through: :followed_users


  has_many :following_users, foreign_key: :friend_id, class_name: 'Follow'
  has_many :followers, through: :following_users



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
  	stocks.count < 10
  end

  def cant_follow_friend?(friend)
    if friends.ids.include?(friend.id)
      return true
    end
    return false
  end

  def stock_already_tracked?(ticker_symbol)
  	stock = Stock.check_db(ticker_symbol)
  	return false unless stock
  	stocks.where(id: stock.id).exists?


  end

  def can_track_stock?(ticker_symbol)
  	under_stock_limit? && !stock_already_tracked?(ticker_symbol)

  end

  def full_name
    return "#{first_name} #{last_name}" if first_name|| last_name
    "Anonymous"

  end 

  def self.search(param)
    param.strip!
    to_send_back = (matches("first_name",param) + 
      matches("last_name",param) + 
      matches("email",param)).uniq
    return nil unless to_send_back
    to_send_back

  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject{|user| user.id==self.id}
  end


end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected


	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

	def create
		current_user.friends.append(User.find(params[:friend_id]))
		redirect_to my_friends_path
	end


	def destroy
		association=Follow.where(follower_id: current_user, friend_id: params[:id])
		association.first.destroy

		flash.now[:notice]="Unfollow complete!"
		respond_to do |format|
			format.js { render :partial => "friends/list" }
			format.html {redirect_to user_path(params[:id])}
		end	
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	

	def search
		if params[:stock].present?
			@stock=Stock.new_lookup(params[:stock])
			if @stock
				render_js	
			else
				flash.now[:alert]='Plese enter a valid symbol'
				render_js
			end
		else
			flash.now[:alert]= 'Please enter a symbol to search'
			render_js
		end
	end


	def update_stocks
		current_user.stocks.each do |stock|
			stock.update_price
		end
		respond_to do |format|
			format.js {render :partial => "stocks/list"}
		end

		#redirect_to my_portfolio_path
	end

	private
	def render_js
		respond_to do |format|
			format.js { render :partial => "users/result" }
		end
	end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

	def create
		stock = Stock.check_db(params[:ticker])
		if stock.blank?
			stock = Stock.new_lookup(params[:ticker])
			stock.save
		end
		@user_stock=UserStock.create(user:current_user, stock:stock)
		flash[:notice]="Stock #{stock.name} was successfully added"
		redirect_to my_portfolio_path
	end


	def destroy
		UserStock.destroy_by(user_id: current_user.id, stock_id: params[:id])
		flash.now[:notice]="#{Stock.find(params[:id]).name} 
				was successfully removed from your portfolio"
		respond_to do |format|
			format.js { render :partial => "stocks/list" }
		end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login

	def my_portfolio

	end

	def my_friends
		
	end

	def show
		@user=User.find(params[:id])
	end


	def search
		User.all.each do |user|
			puts user.id
		end
		if params[:friend_email].blank?
			flash.now[:alert]='Please enter email addres or name'
			render_js
			return false
		end
		@friends=User.search(params[:friend_email])
		if @friends
			@friends=current_user.except_current_user(@friends)
			render_js
		else
			flash.now[:alert]='wrong email addres'
			render_js
		end
	end

	private
	def render_js
		respond_to do |format|
			format.js { render :partial => "follows/result" }
		end
	end

	private
	def require_login
	 if !user_signed_in?
	 	redirect_to root_path
	 end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/follows/_result.html.erb
<%= render :partial => "layouts/messages" %>

<% if @friends %>
	
	
	<div class="card card-header result-block">

		<table class="col-md-12">
			<tbody>
				<% @friends.each do |friend| %>	
					<tr>
						<td><strong>First name:</strong><%= friend.first_name %> &nbsp;&nbsp;</td>
						<td><strong>Last name:</strong><%= friend.last_name %> &nbsp;&nbsp;</td>
						<td><strong>e-mail:</strong><%= friend.email %> &nbsp;&nbsp;</td>
						<%if current_user.cant_follow_friend?(friend) %>

							<td>
							You are Firends
							</td>
							

						<% else %>
						<td>
						<%= link_to "Click to follow", follows_path(friend_id:friend.id), method: :post, class:'btn btn-xs btn-default follow-btn' %>
						</td>
						<% end %>
						<td>
						
						<%= link_to "View Profile", user_path(friend), class:'btn btn-xs btn-default follow-btn' %>

						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>


<% end %>

app/views/follows/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j (render :partial => 'follows/result.html') %>"

app/views/friends/_list.html.erb
<% if current_user.friends.any? %>
	<br>
	<div class="row pl">
		<div class="col-9">
			<table class="table table-bordered table-hover">
			  <thead>
			    <tr>
			      <th scope="col">First name</th>
			      <th scope="col">Second name</th>
			      <th scope="col">e-mail</th>
			      <th scope="col">Actions</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% current_user.friends.each do |friend| %>
			    	<tr>
				      <th><%= friend.first_name %></th>
				      <td><%= friend.last_name %></td>
				      <td><%= friend.email %></td>
				      <td>
				      	<%= link_to "Unfollow", follow_path(friend),method: :delete, remote: true, data: {confirm: "Are you sure?"},class:"btn btn-xs btn-danger" %>
				      	<%= link_to "View Profile", user_path(friend), class:'btn btn-xs btn-default follow-btn' %>
				      </td>
				    </tr>
				 <% end %>
			  </tbody>
			</table>
		</div>
	</div>
<% end %>

app/views/friends/_list.js.erb
document.querySelector('#list').innerHTML = "<%= j (render :partial => 'friends/list.html') %>"

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class="row">
		<div class="col-9">

			<div class='alert alert-success'>
        		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
            		<span aria-hidden="true">&times;</span>
        		</button>
				<%= notice %>
			</div>
		</div>
	</div>
<% end %>

<% if alert %>
	<div class="row">
		<div class="col-9">

			<div class='alert alert-danger'>
        		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
            		<span aria-hidden="true">&times;</span>
        		</button>
				<%= alert %>
			</div>
		</div>
	</div>



<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <li class="<%= 'active-brand' if request.path==root_path%>">
      <%= link_to "Finance Tracker", root_path, class:"navbar-brand"%>
    </li>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path==my_portfolio_path%>">
            
            <%= link_to 'My portfolio', my_portfolio_path, class: "nav-link"%>

          </li>
          <li class="nav-item <%= 'active' if request.path==my_friends_path%>">
            <%= link_to "My friends", my_friends_path, class: "nav-link"%>
          </li>


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit your account', edit_user_registration_path, class:"dropdown-item" %>

              <%= link_to edit_user_registration_path, class:"dropdown-item" do %>
                 <%= fa_icon 'edit' %> Edit your account
              <% end %>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>

        </ul> 
        <ul class="navbar-nav nl-auto">
          <li class="nav-link disabled user-name">
              <%= fa_icon 'user'%>&nbsp;
              <%= current_user.full_name %>
          </li>
          <li class="nav-item">
            <%= link_to( 'Log out', destroy_user_session_path, class: "btn btn-xs btn-danger logout-button", method: :delete )%>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" id="search-btn" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>




  </body>
</html>

app/views/stocks/_list.html.erb
<%= render :partial => 'layouts/messages.html'%>


<% if user.stocks.any? %>
	<br>
	<div class="row">
		<div class="col-9">
			<table class="table table-bordered table-hover">
			  <thead>
			    <tr>
			      <th scope="col">Ticker</th>
			      <th scope="col">Name</th>
			      <th scope="col">Price</th>
			      <th scope="col">Actions</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% user.stocks.each do |stock| %>
			    	<tr>
				      <th><%= stock.ticker %></th>
				      <td><%= stock.name %></td>
				      <td><%= stock.last_price %></td>
				      <td>
				      	<% if current_user.id==user.id %>
				      		<%= link_to "Remove", user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"},class:"btn btn-xs btn-danger",:remote => true %>
				      	<% else %>							
							<% if current_user.can_track_stock?(stock.ticker)%>
								<%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker:stock.ticker), class:'btn btn-xs btn-default', method: :post %>
							<% else %>
								<span class="badge badge-secondary">
									You are already tracking
									<% if !current_user.under_stock_limit? %>
										10 Stocks
									<% end %>
									<% if current_user.stock_already_tracked?(stock.ticker) %>
										<%= stock.name %>
									<% end %>
								</span>
							<% end %>
				      	<% end %>
				      </td>
				      
				    </tr>
				 <% end %>
			  </tbody>
			</table>
		</div>
	</div>
<% end %>

app/views/stocks/_list.js.erb
document.querySelector('#list').innerHTML = "<%= j (render :partial => 'stocks/list.html', :locals =>{user: current_user} )%>"

app/views/users/_result.html.erb
<%= render :partial => "layouts/messages" %>

<% if @stock %>
	<div class="card card-header result-block">		
		<strong>Symbol:</strong> <%= @stock.ticker %> 
		<strong>Name:</strong> <%= @stock.name %> 
		<strong>Price:</strong> <%= @stock.last_price %> 
		<% if current_user.can_track_stock?(@stock.ticker)%>
			<%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker:@stock.ticker), class:'btn btn-xs btn-default', method: :post %>
		<% else %>
			<span class="badge badge-secondary">
				You are already tracking
				<% if !current_user.under_stock_limit? %>
					10 Stocks
				<% end %>
				<% if current_user.stock_already_tracked?(@stock.ticker) %>
					<%= @stock.name %>
				<% end %>
			</span>
		<% end %>
	</div>		
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j (render :partial => 'users/result.html') %>"

app/views/users/my_friends.html.erb
<h3> My Friends </h3>

<div class="search-area">
	<h3> search friend </h3>
	<%= form_tag search_friend_path, method: :get, remote: true do %>

		<div class="form-group row">
			<div class="col-sm-9">
				

				<%= text_field_tag :friend_email, params[:stock], placeholder:'email or name', autofocus:true, class: 'form-control form-control-lg' %>
			</div>
			<div class="col-sm-3" id="search-col">
				<%= button_tag type: :submit, class:'btn btn-default' do %>
					<%= fa_icon "search 2x" %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>
<div id='results'>
</div>

<div id="list">
	<%= render :partial => "friends/list" %>

</div>

app/views/users/my_portfolio.html.erb
<h1> My Portfolio </h1>
<div class="search-area">
	<div class='row'>
		<div class="col-9 col-md-7">

			
		</div>
		<div class="col-3 col-md-2 tc mb-0">

			<%= link_to update_stocks_path, class:'nu', remote: true do %>
				<div class="mb-0"><h3>Update<br>prices</h3></div>
				<%= fa_icon "retweet 5x" %>
			<% end %>
			
		</div>

	</div>
	<h3> search stock </h3>
	<%= form_tag search_stock_path, remote: true, method: :get do %>

		<div class="form-group row">
			<div class="col-sm-9">
				

				<%= text_field_tag :stock, params[:stock], placeholder:'Stock ticker symbol', autofocus:true, class: 'form-control form-control-lg' %>
			</div>
			<div class="col-sm-3" id="search-col">
				<%= button_tag type: :submit, class:'btn btn-default' do %>
					<%= fa_icon "search 2x" %>
				<% end %>
			</div>
		</div>
	<% end %>
	<div id='results'>
		
	</div>
	<div id="list">
		<%= render :partial => 'stocks/list', :locals => {:user => current_user } %>
	</div>
</div>

app/views/users/show.html.erb
<h2> User Details for <%=@user.full_name%>
 </h2>





<div class="row">
  <div class="col-9">

    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">First name</th>
          <th scope="col">Second name</th>
          <th scope="col">e-mail</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
    	<tr>
          <th><%= @user.first_name %></th>
          <td><%= @user.last_name %></td>
          <td><%= @user.email %></td>
    	  <%if current_user.cant_follow_friend?(@user) %>
    		<td>
    			You are friends

    			<%= link_to "Unfollow", follow_path(@user),method: :delete, data: {confirm: "Are you sure?"},class:"btn btn-xs btn-danger" %>
    		</td>

    	  <% else %>

    		<td><%= link_to "Click to follow", follows_path(friend_id:@user), method: :post, class:'btn btn-xs btn-default follow-btn' %>
    		</td>
    	  <% end %>
    		</td>	
        </tr>
      </tbody>
    </table>
  </div>
</div>

<h2> Stocks following by this user </h2>

<%= render :partial => 'stocks/list', :locals => {:user => @user } %>

app/views/welcome/index.html.erb
<h1>Welcome to the finance tracker  app</h1>
<p>Find me in app/views/welcome/index.html.erb</p>




<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

<%= link_to 'log in', new_user_session_path %>